---
#Task: Install CSF
#Filename: main.yml
#Author: Carson Wiens
#Date: 19 January 2015
#Description: Installs and configures the CSF firewall
#Last Modified: 21 January 2015
#Modified by: Stephen Papierski (Taylor University)
#-----------------------------------------------------------------------------------
  # Ensure that we have perl dependency
- name: Installing perl dependency...
  apt: 
     name=libwww-perl
     state=latest     

- name: Downloading CSF...
  shell: rm -f csf.tgz
  shell: wget http://www.configserver.com/free/csf.tgz
  
- name: Untaring CSF
  shell: tar -xzf csf.tgz

- name: Installing CSF
  shell: sh ./install.sh
  args:
      chdir: csf

  # Run the csf test script with perl
- name: Running the CSF test script...
  shell:
     perl /etc/csf/csftest.pl >> testResult.txt

  # test output of csf test script for missing modules. Output.
- name: Missing CSF modules!
  shell: 
     echo 'missing module(s)! Search for FATAL in testResult.txt.'
  when:
     shell: grep -e "*FATAL*" testResult.txt

  # Modify csf.conf according to the standards in our 'Palaso Servers' google doc
- name: Modifying firewall settings in csf.conf...
  copy: src=./../files/csf.conf dest=/etc/csf/csf.conf backup=yes

  # Modify csf.allow to allow some common outbound IP addresses
- name: Appending some commonly used IP addresses to csf.allow...
  copy: src=./../files/csf.allow dest=/etc/csf/csf.allow backup=yes

  # Restart csf to solidify the changes
- name: Restarting CSF...
  shell:
     csf -r

  # Start the lfd daemon
- name: Starting LFD...
  shell:
     /etc/init.d/lfd start
