---

- user: name={{ item.name }} group=staff password={{ item.password | default('$6$Vw82JDwSS$X/JslDUp1pUsFjJmmFyDY95UFD7lclVEhiJSqFt1nDydxLdKrHrmvcs1OnQS.a7DU7qzAfKajFy8rqdtiUdXj1') }}
  with_items: "{{user_accounts}}"
 
- authorized_key: user="{{ item.0.name }}" key="{{ item.1 }}"
  with_subelements:
    - user_accounts
    - authorized
