---
# Configures the CSF firewall

- stat: path=/etc/csf/csf.conf
  register: csf_stat
  
- fail: msg="csf is not installed"
  when: not csf_stat.stat.exists

# General CSF Configuration
- lineinfile: 
    dest: /etc/csf/csf.conf
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^TESTING =', line: 'TESTING = "{{csf_config_testing}}"' }
    - { regexp: '^TCP_IN =', line: 'TCP_IN = "{{csf_config_ports.tcp4_in|join(",")}}"' }
    - { regexp: '^TCP_OUT =', line: 'TCP_OUT = "{{csf_config_ports.tcp4_out|join(",")}}"' }
    - { regexp: '^UDP_IN =', line: 'UDP_IN = "{{csf_config_ports.udp4_in|join(",")}}"' }
    - { regexp: '^UDP_OUT =', line: 'UDP_OUT = "{{csf_config_ports.udp4_out|join(",")}}"' }
    - { regexp: '^TCP6_IN =', line: 'TCP6_IN = "{{csf_config_ports.tcp4_in|join(",")}}"' }
    - { regexp: '^TCP6_OUT =', line: 'TCP6_OUT = "{{csf_config_ports.tcp4_out|join(",")}}"' }
    - { regexp: '^UDP6_IN =', line: 'UDP6_IN = "{{csf_config_ports.udp4_in|join(",")}}"' }
    - { regexp: '^UDP6_OUT =', line: 'UDP6_OUT = "{{csf_config_ports.udp4_out|join(",")}}"' }
    - { regexp: '^ETH_DEVICE =', line: 'ETH_DEVICE = "{{csf_config_device}}"' }
    - { regexp: '^DENY_IP_LIMIT =', line: 'DENY_IP_LIMIT = "100"' }
    - { regexp: '^LF_LOOKUPS =', line: 'LF_LOOKUPS = "1"' }
    - { regexp: '^SMTP_BLOCK =', line: 'SMTP_BLOCK = "1"' }
    - { regexp: '^SMTP_ALLOWUSER =', line: 'SMTP_ALLOWUSER = "postfix"' }
    - { regexp: '^SMTP_ALLOWGROUP =', line: 'SMTP_ALLOWGROUP = "mail,postfix"' }
    - { regexp: '^URLGET =', line: 'URLGET = "1"' }
    - { regexp: '^LF_SSH_EMAIL_ALERT =', line: 'LF_SSH_EMAIL_ALERT = "{{csf_config_alert_ssh_email}}"' }
    - { regexp: '^LF_INTERVAL =', line: 'LF_INTERVAL = "{{csf_config_lfd_interval}}"' }
    - { regexp: '^LF_DISTFTP =', line: 'LF_DISTFTP = "{{csf_config_lfd_dist_ftp.limit}}"' }
    - { regexp: '^LF_DISTFTP_UNIQ =', line: 'LF_DISTFTP_UNIQ = "{{csf_config_lfd_dist_ftp.unique}}"' }
    - { regexp: '^LF_DISTFTP_PERM =', line: 'LF_DISTFTP_PERM = "{{csf_config_lfd_dist_ftp.time}}"' }
    - { regexp: '^LF_DISTFTP_ALERT =', line: 'LF_DISTFTP_ALERT = "{{csf_config_lfd_dist_ftp.alert}}"' }
    - { regexp: '^PT_USERKILL =', line: 'PT_USERKILL = "{{csf_config_user_kill.enabled}}"' }
    - { regexp: '^PT_USERKILL_ALERT =', line: 'PT_USERKILL_ALERT = "{{csf_config_user_kill.alert}}"' }
    - { regexp: '^PT_USER_ACTION =', line: 'PT_USER_ACTION = "{{csf_config_user_kill.action}}"' }
    - { regexp: '^PS_INTERVAL =', line: 'PS_INTERVAL = "{{csf_config_port_scan.interval}}"' }
    - { regexp: '^PS_LIMIT =', line: 'PS_LIMIT = "{{csf_config_port_scan.limit}}"' }
    - { regexp: '^PORTKNOCKING_ALERT =', line: 'PORTKNOCKING_ALERT = "{{csf_config_port_knocking.alert}}"' }
    - { regexp: '^ST_SYSTEM =', line: 'ST_SYSTEM = "{{csf_config_system.enabled}}"' }
    - { regexp: '^LF_WEBMIN_EMAIL_ALERT =', line: 'LF_WEBMIN_EMAIL_ALERT = "0"' }
    # - { regexp: '^', line: '' }

# Configure the LFD checks. Each named check has a limit on hits after which ip will be blocked for time seconds.
- lineinfile: 
    dest: /etc/csf/csf.conf
    regexp: '^LF_{{item.name}} ='
    line: 'LF_{{item.name}} = "{{item.limit}}"'
  with_items:
    csf_config_lfd_blocks

- lineinfile: 
    dest: /etc/csf/csf.conf
    regexp: '^LF_{{item.name}}_PERM ='
    line: 'LF_{{item.name}}_PERM = "{{item.time}}"'
  with_items:
    csf_config_lfd_blocks

# Configure the location of the logfiles
- lineinfile: 
    dest: /etc/csf/csf.conf
    regexp: '^{{item.name}}_LOG ='
    line: '{{item.name}}_LOG = "{{item.file}}"'
  with_items:
    csf_config_logs
      
# Configure the location of the custom logfiles
- lineinfile: 
    dest: /etc/csf/csf.conf
    regexp: '^{{item.name}}_LOG ='
    line: '{{item.name}}_LOG = "{{item.file}}"'
  with_items:
    csf_config_logs_custom

# Template the csf.pignore
- template:
    dest: /etc/csf/csf.pignore
    src: csf.pignore.j2

# Copy any custom rules
- copy:
    dest: /usr/local/csf/bin/
    src: regex.custom.pm
