- lineinfile: 
    dest: /etc/locale.gen
    regexp: "{{item}}"
    line: "{{item}}"
  with_items:
    locale_install_locales
  when: "'{{ansible_os_family}}' == 'debian'"

- command: locale-gen
  when: "'{{ansible_os_family}}' == 'debian'"

