- name: Authprogs Configuration
  copy: src="site_files/{{inventory_hostname}}/root/.ssh/authprogs.conf" dest="/root/test/"
  
- name: Authprogs Keys
  copy: src="site_files/{{inventory_hostname}}/root/.ssh/authorized_keys" dest="/root/test/"
