---
# Installs and configures the CSF firewall
# Authors: Carson Wiens, Stephen Papierski, Cambell Prince

- stat: path=/etc/csf/csf.conf
  register: csf_stat

- include: install.yml
  when: not csf_stat.stat.exists
  
