---

- name: Install packages.
  apt: name=openssl state=present
  # when: ansible_os_family == "Debian"
  
- name: Ensure ssl path exist
  file: path={{ssl_path}} state=directory owner="{{ssl_path_owner | default('root')}}" group="{{ssl_path_group | default('root')}}" mode=700
  
